name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the `main` branch.

jobs:
  lint:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment.

    steps:
    # Step 1: Checkout the current code in the repository.
    - name: Checkout repository
      uses: actions/checkout@v2  # Fetch the repository contents.

    # Step 2: Run Super Linter to check changed files for linting issues.
    - name: Lint Code Base
      uses: github/super-linter@v4.9.7  # Use the Super Linter GitHub Action.
      env:
        VALIDATE_TERRAFORM: true  # Enable Terraform validation.
        VALIDATE_ALL_CODEBASE: false  # Only validate changed files.
        VALIDATE_MARKDOWN: false  # Example: Disable markdown validation (customize as needed).
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication.
        FILTER_REGEX_EXCLUDE: ''  # Optional: Exclude certain files or paths.
        IGNORE_GITIGNORED_FILES: true  # Ignore files listed in .gitignore.

    # Step 3: Install Terraform CLI for managing infrastructure as code.
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1  # Install Terraform using the official HashiCorp setup action.
      with:
        terraform_version: 1.1.5  # Specify the version of Terraform to use (optional).

    # Step 4: Run Terraform Format (terraform fmt) to check code formatting.
    - name: Check Terraform Formatting
      run: terraform fmt -check  # Check if the Terraform files are formatted correctly.

    # Step 5: Run Terraform Validate to check if the configuration is syntactically valid.
    - name: Validate Terraform
      run: terraform validate  # Validate the Terraform configuration.

    # Step 6: Install TFLint for checking Terraform code quality and best practices.
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash  # Install TFLint.

    # Step 7: Run TFLint to lint the Terraform configuration.
    - name: Run TFLint
      run: tflint  # Lint Terraform files using TFLint.
