name: Lint Code Base
permissions: {}

# Trigger the workflow only on pull requests targeting the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    # Permissions required for the job
    permissions:
      contents: read  # Allows reading repository contents
      statuses: write # Allows posting status updates

    steps:
      # Step to check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch the full git history for accurate linting
          fetch-depth: 0

      # Step to run Super-Linter
      - name: Lint Code Base
        uses: super-linter/super-linter@v7
        env:
          # The default branch to compare against (for pull request reviews)
          DEFAULT_BRANCH: main
          
          # Whether to disable error reporting
          DISABLE_ERRORS: false

          # GitHub token for accessing repository contents
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Only validate Terraform files
          VALIDATE_ALL_CODEBASE: false
          
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_TERRASCAN: true  
          VALIDATE_CHECKOV: true  
